language: java
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

branches:
    - master

# commands that need to be run before installing the dependencies
before_install:
  - REPO_LOCATION=$("pwd")
#  - sudo chmod +x ./cova/localLibs/install_local_libs.sh is now +x in repo
  - ./cova/localLibs/install_local_libs.sh
  - export LD_LIBRARY_PATH="$REPO_LOCATION/cova/localLibs/z3-4.5.0-x64-ubuntu/bin"
  - echo $LD_LIBRARY_PATH
  - stat $LD_LIBRARY_PATH
  - echo $JAVA_HOME
  - ls -a $JAVA_HOME
  - ls -a $JAVA_HOME/lib
#  - stat $JAVA_HOME/lib/rt.jar

install: true
script: mvn clean install 


